sudo: required
services:
    - docker

before_install:
    - docker build -t razorlight/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run razorlight/react-test npm test -- --coverage

after_success:
    - docker build -t razorlight/multi-client ./client
    - docker build -t razorlight/multi-nginx ./nginx
    - docker build -t razorlight/multi-server ./server
    - docker build -t razorlight/multi-worker ./worker
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push razorlight/multi-client
    - docker push razorlight/multi-nginx
    - docker push razorlight/multi-server
    - docker push razorlight/multi-worker
